#!/bin/bash
# connect_irc.sh

user=("one", "two", "three")
channel=("AAA", "BBB", "CCC")

{
    sleep 1
    echo "PASS 7979"
    echo "USER $1"  
    echo "NICK $1"
    echo "join #$2"
    cat  
} | nc -C 127.0.0.1 7979