#ifndef RULE_HPP
#define RULE_HPP

typedef enum{
    RPL_WELCOME = 1,
    RPL_YOURHOST,
    RPL_CREATED,
    RPL_MYINFO,
    
    JOIN = 100,
    NICK,
    USER,
    QUIT,
    PART,
    PRIVMSG,
    NOTICE,
    PASS,
    LIST,
    SHOW,

    ERR_UNKNOWNERROR = 400,
    ERR_NOSUCHNICK,
    ERR_NOSUCHSERVER,
    ERR_NOSUCHCHANNEL,
    ERR_NOSUCHCOMMAND,
    ERR_EMPTY,
    ERR_NOSUCHMODEOPTION,
    ERR_CANNOTSENDTOCHAN,
    ERR_TOOMANYCHANNELS,
    ERR_TOOMANYTARGETS,
    ERR_TOOMANYCAHR,
    ERR_NICKNAMEINUSE,
    ERR_FATAL,
    
    OK = 777,

    KICK = 1000,
    INVITE,
    TOPIC,
    MODE,

    // DCC 명령어들 추가
    DCC_SEND = 2000,
    DCC_ACCEPT,
    DCC_RESUME,
    DCC_REJECT,

    MODE_INVITESET = 2001,
    MODE_INVITERM,
    MODE_TOPICSET,
    MODE_TOPICRM,
    MODE_KEYSET,
    MODE_KEYRM,
    MODE_OWNERGIVE,
    MODE_OWNERTAKE,
    MODE_LIMITSET,
    MODE_LIMITRM,
} user_role;

#endif